### ISSUE TITLE
Fix nyxtmuch--select-message-body for HTML-less bodies

### ISSUE THREAD

**Issue by Ambrevar** [igoralmeida/nx-notmuch#1]
Currently nyxtmuch--select-message-body fails if email has no HTML body.

Suggestion:

```lisp
(defun nyxtmuch--select-message-body (mime)
  "Prefer HTML over plaintext, if multipart."
  (flet ((mime->string (m)
           (str:concat
            (cl-mime:content-type m) "/" (cl-mime:content-subtype m))))
    (if (equal (cl-mime:content-type mime) "multipart")
        (or (find-if (serapeum:equals "text/html")
                     (cl-mime:content mime)
                     :key #'mime->string)
            (find-if (serapeum:equals "text/plain")
                     (cl-mime:content mime)
                     :key #'mime->string))
        mime)))
```

Alternatively:

```lisp
(defun nyxtmuch--select-message-body (mime)
  "Prefer HTML over plaintext, if multipart."
  (flet ((mime->string (m)
           (str:concat
            (cl-mime:content-type m) "/" (cl-mime:content-subtype m))))
    (if (equal (cl-mime:content-type mime) "multipart")
        (let ((parts (serapeum:partitions (list (serapeum:equals "text/html")
                                                (serapeum:equals "text/plain"))
                                          (cl-mime:content mime)
                                          :key #'mime->string)))
          (first (or (first parts)
                     (second parts))))
        mime)))
```

**Comment by igoralmeida** [comment]
Interesting, my early tests worked for very simple `text/plain` messages, but even these versions have problems with deep `multipart/mixed` and `multipart/signed` trees (it'll for example render only the plaintext signature at the end of the message).

I think the simplest implementation right now is to just show every [reasonable] part, unless it's `multipart/alternative` (in which case you prefer html over plain).

Even so, it's important to note that there's currently no way to tell the render function that `text/plain` parts should be preformatted (for example), it just becomes a long string.
It might be possible to add some sort of token to the message and style the div with `white-space: pre`. It looks ok-ish with the inspector at least.

**Comment by igoralmeida** [comment]
Some hiccups (charsets, attachments), but working...

| ![2021-04-30-215410_467x1052_scrot](https://user-images.githubusercontent.com/40757/116767267-818d1f80-aa05-11eb-9091-4047874935cf.png) | ![2021-04-30-224309_403x927_scrot](https://user-images.githubusercontent.com/40757/116767268-82be4c80-aa05-11eb-828a-fc58ba5eaa8f.png) |
| ----- | ----- |

**Comment by Ambrevar** [comment]
Looking fantastic!  Thank you so much for you work on this!
